// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrueNasAppManager.Data;

#nullable disable

namespace TrueNasAppManager.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("TrueNasAppManager.Domain.AppContainerRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NetworksJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("VolumesJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId", "ContainerId");

                    b.ToTable("AppContainers");
                });

            modelBuilder.Entity("TrueNasAppManager.Domain.AppPortRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ContainerPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HostIp")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("HostPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId", "HostPort", "Protocol");

                    b.ToTable("AppPorts");
                });

            modelBuilder.Entity("TrueNasAppManager.Domain.AppPortalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("AppPortals");
                });

            modelBuilder.Entity("TrueNasAppManager.Domain.UptimeKumaMonitorRecord", b =>
                {
                    b.Property<string>("MonitorId").HasMaxLength(128).HasColumnType("TEXT");
                    b.Property<string>("AppId").HasMaxLength(256).HasColumnType("TEXT");
                    b.Property<double?>("AverageResponseTimeMilliseconds1Day").HasColumnType("REAL");
                    b.Property<double?>("AverageResponseTimeMilliseconds30Days").HasColumnType("REAL");
                    b.Property<double?>("AverageResponseTimeMilliseconds365Days").HasColumnType("REAL");
                    b.Property<double?>("CertificateDaysRemaining").HasColumnType("REAL");
                    b.Property<bool?>("CertificateIsValid").HasColumnType("INTEGER");
                    b.Property<string>("Hostname").HasMaxLength(512).HasColumnType("TEXT");
                    b.Property<bool>("IsPresent").HasColumnType("INTEGER");
                    b.Property<DateTime>("LastSeenUtc").HasColumnType("TEXT");
                    b.Property<string>("Name").IsRequired().HasMaxLength(256).HasColumnType("TEXT");
                    b.Property<int?>("Port").HasColumnType("INTEGER");
                    b.Property<double?>("ResponseTimeMilliseconds").HasColumnType("REAL");
                    b.Property<string>("Status").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Type").IsRequired().HasMaxLength(64).HasColumnType("TEXT");
                    b.Property<double?>("UptimeRatio1Day").HasColumnType("REAL");
                    b.Property<double?>("UptimeRatio30Days").HasColumnType("REAL");
                    b.Property<double?>("UptimeRatio365Days").HasColumnType("REAL");
                    b.Property<string>("Url").HasMaxLength(2048).HasColumnType("TEXT");
                    b.HasKey("MonitorId");
                    b.HasIndex("AppId");
                    b.ToTable("UptimeKumaMonitors");
                });

            modelBuilder.Entity("TrueNasAppManager.Domain.AppRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ActionRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CatalogUpdateAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("DowntimeAction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DowntimeNotificationActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("HealthIncidentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthMessage")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("HumanVersion")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ImageUpdateAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstalledVersion")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInstalled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCheckUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastHealthCheckUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSuccessfulUpdateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestHumanVersion")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestVersion")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPortalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MaintenanceMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManualPortalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MissingSinceUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyOnDowntime")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("NotifySuccessOverride")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutdatedImagesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Policy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RecoveryAttemptedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemotePortalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SnapshotHostPaths")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUrlsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusLabel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Train")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionScope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("TrueNasAppManager.Domain.GitHubRepositoryCache", b =>
                {
                    b.Property<string>("RepositoryUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ETag")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAttemptUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastFetchedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("License")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Stars")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopicsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("RepositoryUrl");

                    b.ToTable("GitHubRepositories");
                });

            modelBuilder.Entity("TrueNasAppManager.Domain.NotificationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeliveredUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeduplicationKey", "Provider", "Status");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TrueNasAppManager.Domain.SettingsRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowInsecureWebSocket")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectionFailureCooldownMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CronExpression")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailFromAddress")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailFromName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailRecipientsJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("GitHubEnrichmentEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HistoryRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCompletedCheckUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastConnectionError")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastConnectionErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUptimeKumaError")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUptimeKumaSuccessUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUptimeKumaSyncUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastConnectionSuccessUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastInventoryRefreshUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastScheduledRunUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagerAppId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyAutomaticBlocked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyAutomaticFailure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyAutomaticSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyConnectionFailure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyManualApproval")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyRollback")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyScheduledCheckFailure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OnboardingStep")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PortalHostOverride")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SchedulerEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpHost")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPasswordEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpSecurity")
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpUsername")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrueNasApiKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrueNasUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrueNasUsername")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("UptimeKumaApiKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("UptimeKumaBaseUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("UptimeKumaBrowserUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UptimeKumaEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UptimeKumaRefreshIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UptimeKumaVerifyTls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VerificationTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VerifyTls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebhookAuthorizationEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WebhookEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebhookHeadersEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<int>("WebhookTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("TrueNasAppManager.Domain.UpdateAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("FromVersion")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutdatedImagesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyAtExecution")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonMessage")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeAtExecution")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SnapshotRequested")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToVersion")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TrueNasJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrueNasJobState")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("AppId", "StartedUtc");

                    b.ToTable("UpdateAttempts");
                });

            modelBuilder.Entity("TrueNasAppManager.Domain.UptimeKumaMonitorRecord", b =>
                {
                    b.HasOne("TrueNasAppManager.Domain.AppRecord", "App")
                        .WithMany("UptimeKumaMonitors")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("App");
                });

            modelBuilder.Entity("TrueNasAppManager.Domain.UpdateRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CheckedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EligibleCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SucceededCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedUtc");

                    b.ToTable("UpdateRuns");
                });

            modelBuilder.Entity("TrueNasAppManager.Domain.AppContainerRecord", b =>
                {
                    b.HasOne("TrueNasAppManager.Domain.AppRecord", "App")
                        .WithMany("Containers")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("TrueNasAppManager.Domain.AppPortRecord", b =>
                {
                    b.HasOne("TrueNasAppManager.Domain.AppRecord", "App")
                        .WithMany("Ports")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("TrueNasAppManager.Domain.AppPortalRecord", b =>
                {
                    b.HasOne("TrueNasAppManager.Domain.AppRecord", "App")
                        .WithMany("Portals")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("TrueNasAppManager.Domain.UpdateAttempt", b =>
                {
                    b.HasOne("TrueNasAppManager.Domain.AppRecord", "App")
                        .WithMany("Attempts")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrueNasAppManager.Domain.UpdateRun", "Run")
                        .WithMany("Attempts")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("TrueNasAppManager.Domain.AppRecord", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Containers");

                    b.Navigation("Portals");

                    b.Navigation("Ports");

                    b.Navigation("UptimeKumaMonitors");
                });

            modelBuilder.Entity("TrueNasAppManager.Domain.UpdateRun", b =>
                {
                    b.Navigation("Attempts");
                });
#pragma warning restore 612, 618
        }
    }
}
